# NAIVE BAYES

### IMPORT DATASET

In [2]:
%matplotlib inline
import pandas
import matplotlib.pyplot as plt
import numpy as np
X = pandas.read_csv('X.csv', sep=',', na_values="")
y = pandas.read_csv('y.csv', sep=',', na_values="")
print(X.head())
print(y.head())

   abc  abl  abolish  absolut  accept  accord  account  across  act  action  \
0    0    0        0        0       0       0        0       0    0       0   
1    0    0        0        0       0       0        0       0    0       0   
2    0    0        0        0       0       0        0       0    0       0   
3    0    0        0        0       0       0        0       0    0       0   
4    0    0        0        0       0       0        0       0    0       0   

   ...  york  yorker  youll  young  your  youv  yuge  zero  zogbi  zone  
0  ...     0       0      0      0     0     0     0     0      0     0  
1  ...     0       0      0      0     0     0     0     0      0     0  
2  ...     0       0      0      0     0     0     0     0      0     0  
3  ...     0       0      0      0     0     0     0     0      0     0  
4  ...     0       0      0      0     0     0     0     0      0     0  

[5 rows x 1477 columns]
   Viral
0      2
1      2
2      2
3      2
4      2


In [4]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score, train_test_split
import sklearn.neighbors as nb

# Asegurarse de que y es un array unidimensional
y = y.values.ravel()

# Configuración de la validación cruzada
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)

# Inicializar el clasificador Naive Bayes
mnb = MultinomialNB()
gnb = GaussianNB()

# Realizar validación cruzada
cv_scoresm = cross_val_score(mnb, X=X, y=y, cv=cv)
cv_scoresg = cross_val_score(gnb, X=X, y=y, cv=cv)

# Mostrar la puntuación media
print(np.mean(cv_scoresm))
print(np.mean(cv_scoresg))

0.5670500049640931
0.4673943659382319


### CONFUSION MATRIX AND ACCURACY

In [13]:
from sklearn.model_selection import cross_val_predict  
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

predictedm = cross_val_predict(MultinomialNB(), X=X, y=y,  cv=cv)  
predictedg = cross_val_predict(GaussianNB(), X=X, y=y,  cv=cv) 

print(confusion_matrix(y, predictedm))
print(accuracy_score(y, predictedm))

print(confusion_matrix(y, predictedg))
print(accuracy_score(y, predictedg))

[[1285  601  749]
 [ 556 1621  291]
 [ 709  287 1276]]
0.5670508474576271
[[ 338  438 1859]
 [ 198 1157 1113]
 [ 134  186 1952]]
0.4673898305084746


### PRECISION , RECALL, F1-SCORE

In [14]:
from sklearn.metrics import classification_report

print(classification_report(y, predictedm))
print(classification_report(y, predictedg))

              precision    recall  f1-score   support

    moderado       0.50      0.49      0.50      2635
       mucho       0.65      0.66      0.65      2468
        poco       0.55      0.56      0.56      2272

    accuracy                           0.57      7375
   macro avg       0.57      0.57      0.57      7375
weighted avg       0.57      0.57      0.57      7375

              precision    recall  f1-score   support

    moderado       0.50      0.13      0.20      2635
       mucho       0.65      0.47      0.54      2468
        poco       0.40      0.86      0.54      2272

    accuracy                           0.47      7375
   macro avg       0.52      0.49      0.43      7375
weighted avg       0.52      0.47      0.42      7375

